/**
 * Generate Copilot configuration files for developers
 * Creates copilot-instructions.md and agent mode content with MCP server config
 */

const fs = require("fs");
const path = require("path");

const getBaseUrl = () => {
  // Use environment variable or default to localhost
  return process.env.HUB_BASE_URL || process.env.BASE_URL || `http://localhost:${process.env.PORT || 5000}`;
};

/**
 * Generate the MCP server configuration JSON
 */
const generateMcpConfig = (project, apiKeyPreview = "YOUR_API_KEY") => {
  const baseUrl = getBaseUrl();
  const serverName = `${project.name.toLowerCase().replace(/\s+/g, "-")}-hub`;

  return {
    mcpServers: {
      [serverName]: {
        url: `${baseUrl}/api/mcp/sse`,
        transport: "sse",
        headers: {
          "x-api-key": apiKeyPreview,
        },
      },
    },
  };
};

/**
 * Generate the VS Code settings.json snippet for MCP
 */
const generateVsCodeSettings = (project, apiKeyPreview = "YOUR_API_KEY") => {
  const mcpConfig = generateMcpConfig(project, apiKeyPreview);

  return {
    "github.copilot.chat.codeGeneration.instructions": [
      {
        file: ".github/copilot-instructions.md",
      },
    ],
    "mcp": mcpConfig,
  };
};

/**
 * Generate copilot-instructions.md content
 */
const generateCopilotInstructions = (project, options = {}) => {
  const baseUrl = getBaseUrl();
  const apiKeyPreview = options.apiKeyPreview || "YOUR_API_KEY";
  const mcpConfig = generateMcpConfig(project, apiKeyPreview);
  const conventions = options.conventions || project.conventions || "";

  const content = `# ${project.name} - Copilot Instructions

This file configures GitHub Copilot to work with your project's Knowledge Hub.

## MCP Server Configuration

Add this to your VS Code \`settings.json\` to connect Copilot to the Knowledge Hub:

\`\`\`json
${JSON.stringify(mcpConfig, null, 2)}
\`\`\`

**Important:** Replace \`YOUR_API_KEY\` with your personal API key from the Knowledge Hub.

## Available MCP Tools

Once connected, you can use these tools in Copilot Chat:

### \`search_hub\`
Search the knowledge hub for project codes, documents, SRS, user stories, epics, bugs, and project information.

**Example prompts:**
- "Search the hub for authentication implementation"
- "Find user stories related to payment processing"
- "What does the SRS say about performance requirements?"

### \`get_my_activity\`
Review what you've been working on recently.

**Example prompts:**
- "What was I working on last week?"
- "Show my recent activity"

### \`get_team_activity\` (PM/Admin only)
See what the team has been working on.

**Example prompts:**
- "What has the team been working on this week?"
- "Show team activity summary"

### \`get_developer_context\`
Get context for taking over another developer's work (handoff scenarios).

**Example prompts:**
- "What was John working on before his leave?"
- "Get handoff context for Sarah"

## Project Conventions

${conventions || "No specific conventions defined. Ask the Knowledge Hub for coding standards."}

## Getting Started

1. **Get your API key**: Ask your admin to create an API key assigned to you
2. **Configure VS Code**: Add the MCP configuration above to your settings
3. **Start chatting**: Use Copilot Chat with @ mentions to query the hub

## Tips

- Use \`@workspace\` to search your local codebase
- Use the Knowledge Hub tools for project documentation and standards
- When stuck, ask: "Search the hub for [your topic]"
- For handoffs, use: "Get handoff context for [developer name]"

---

*Generated by Knowledge Hub for ${project.name}*
*Hub URL: ${baseUrl}*
`;

  return content;
};

/**
 * Generate the VS Code agent mode configuration (agents.json)
 */
const generateAgentConfig = (project, apiKeyPreview = "YOUR_API_KEY") => {
  const serverName = `${project.name.toLowerCase().replace(/\s+/g, "-")}-hub`;

  return {
    "projetai-dev": {
      instructions: ".github/agents/projetai-dev.md",
      tools: [`mcp::${serverName}`],
      description: `Pro-jet.ai Dev Agent for ${project.name} — search project knowledge, user stories, docs, and codebase`,
    },
  };
};

/**
 * Load the agent template content and customize it for the project
 */
const generateAgentInstructions = (project) => {
  const templatePath = path.join(__dirname, "..", "agent-templates", "projetai-dev-agent.md");
  
  try {
    let content = fs.readFileSync(templatePath, "utf-8");
    // Customize the template with project-specific info
    content = content.replace(/Pro-jet\.ai Dev Agent/g, `${project.name} Dev Agent`);
    return content;
  } catch (err) {
    console.warn("Agent template not found, using inline template");
    return generateFallbackAgentInstructions(project);
  }
};

/**
 * Fallback agent instructions if template file not found
 */
const generateFallbackAgentInstructions = (project) => {
  return `# ${project.name} Dev Agent

You are a senior software engineer AI assistant connected to the **${project.name}** Digital Knowledge Hub via MCP.

## Key Principle: RAG-First

**ALWAYS call \`search_hub\` FIRST** for any project question. The Knowledge Hub contains indexed source code, documents, user stories, architecture docs, and more.

## Available Tools

| Tool | Purpose |
|------|---------|
| \`search_hub\` | Search the Knowledge Hub — **use FIRST** |
| \`get_my_activity\` | Recall your recent work |
| \`get_team_activity\` | Team progress (PM/Admin) |
| \`get_developer_context\` | Handoff context |

## What You Can Do

1. **User Stories & Requirements** — Find stories, epics, bugs, acceptance criteria
2. **Project Documentation** — Search SRS, architecture docs, API specs
3. **Codebase Understanding** — Find code patterns, explain implementations
4. **Implementation Assistance** — Follow project conventions from the KB
5. **Developer Handoff** — Get context when taking over work
6. **Code Review Context** — Cross-reference changes against requirements

## Guidelines

- Ground answers in hub data
- Be specific — reference exact documents and files
- Admit gaps — if the hub lacks info, say so
- No hallucination — don't fabricate answers
`;
};

/**
 * Generate a complete configuration package
 */
const generateConfigPackage = (project, options = {}) => {
  const apiKeyPreview = options.apiKeyPreview || "YOUR_API_KEY";

  return {
    project: {
      id: String(project._id),
      name: project.name,
    },
    files: {
      "copilot-instructions.md": {
        path: ".github/copilot-instructions.md",
        content: generateCopilotInstructions(project, options),
      },
      "projetai-dev.md": {
        path: ".github/agents/projetai-dev.md",
        content: generateAgentInstructions(project),
      },
    },
    mcpConfig: generateMcpConfig(project, apiKeyPreview),
    agentConfig: generateAgentConfig(project, apiKeyPreview),
    vsCodeSettings: generateVsCodeSettings(project, apiKeyPreview),
    instructions: {
      setup: [
        "1. Copy copilot-instructions.md to .github/copilot-instructions.md in your project",
        "2. Copy projetai-dev.md to .github/agents/projetai-dev.md for the custom agent mode",
        "3. Add the MCP configuration to .vscode/mcp.json",
        "4. Replace YOUR_API_KEY with your personal API key",
        "5. Reload VS Code — use @projetai-dev in Copilot Chat to activate the agent",
      ],
      apiKey: "Request an API key from your project admin. Make sure it's assigned to your user account for activity tracking.",
    },
  };
};

module.exports = {
  generateCopilotInstructions,
  generateAgentInstructions,
  generateAgentConfig,
  generateMcpConfig,
  generateVsCodeSettings,
  generateConfigPackage,
  getBaseUrl,
};
